export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_MEN_ITEMS = "GET_MEN_ITEMS";
export const GET_WOMEN_ITEMS = "GET_WOMEN_ITEMS";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
